name: Spring Library CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test and Build
      run: |
        ./gradlew test
        ./gradlew bootJar

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy to Heroku using Git
      env:
        HEROKU_API: ${{ secrets.HEROKU_API }}
      run: |
        git init
        git config --global user.email "alam.imran21510@gmail.com"
        git config --global user.name "GitHub Actions"
        git fetch --all --unshallow || echo "Repository is already full clone"
        git remote add heroku https://heroku:${HEROKU_API}@git.heroku.com/spring-library-app.git
        git checkout main
        git push heroku HEAD:main -f
