name: Spring Boot CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test and Build
      run: |
        ./gradlew test
        ./gradlew bootJar

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate with Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku auth:token

    - name: Deploy to Heroku using Git
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git init
        git config --global user.email "alam.imran21510@gmail.com"
        git config --global user.name "GitHub Actions"
        heroku git:remote -a your-heroku-app
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Deploying to Heroku"
          git push heroku HEAD:main -f
        else
          echo "No changes to deploy"
        fi

